version: '3'

services:
  timshel_admin:
    image: ghcr.io/intuition-business/timshel/admin:production
    ports:
      - "3001:3001"
    restart: always
    environment:
      - NODE_ENV=production
